config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :feedbacks
  # Defines the root path route ("/")
  root 'projects#index'
  devise_for :users
  resources :projects
  resources :project_updates, only: [:edit, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Project < ApplicationRecord
  # ASSOCIATIONS
  has_many :project_updates, dependent: :destroy, autosave: true
  # ATTEMPT TO BE MORE EFFICIENT
  # has_one :latest_update, lambda {
  #                           ProjectUpdate.latest_updates_for_projects
  #                         }, class_name: 'ProjectUpdate', inverse_of: :project, dependent: :destroy
  has_many :project_access_controls, dependent: :destroy
  has_many :users, through: :project_access_controls

  # NESTED ATTRIBUTES
  accepts_nested_attributes_for :project_updates

  # VALIDATIONS
  validates :name, presence: true

  # TODO: COUPLING !!
  def owner_ids
    ProjectAccessControl.where(project_id: id, level: 'owner').map(&:user_id)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# The Controller for manipulating Projects
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_times, only: %i[show]
  before_action :authenticate_user!
  before_action :authorize_user, except: %i[show edit index]

  def index
    @projects = policy_scope(Project).includes(:project_updates).all
    @new_project = Project.new
  end

  # GET /projects/1 or /projects/1.json
  def show; end

  # GET /projects/1/edit
  def edit
    @project_update = ProjectUpdate.new
    @status_change_type = params[:status_change_type]
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if project_save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :index, status: :created, location: @project }
      else
        format.html { render :index, status: :unprocessable_entity, alert: @project.errors.full_messages }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        # TODO: FIXME - THIS IS TERRIBLE
        @project.project_updates.last.update(status: 'finished') if params[:finished] == 'true'
        format.html { redirect_to project_url(@project), notice: 'Project was successfully updated.' }
        format.json { render :index, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity, alert: @project.errors.full_messages }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def authorize_user
    project = @project || Project
    authorize(project)
  end

  def project_params
    params.require(:project).permit(:name,
                                    project_updates_attributes: %i[status reason note is_start manually_edited_date
                                                                   manually_edited_time])
  end

  # Wraps the save and the access control in a transaction so that
  # either both are saved or neither
  def project_save
    ActiveRecord::Base.transaction do
      @project.save!
      @project_access_control = ProjectAccessControl.new(project: @project, user: current_user,
                                                         level: ProjectAccessControl.levels.fetch('owner'))
      @project_access_control.save!
    end
  end

  def set_project
    @project = policy_scope(Project).includes(:project_updates).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to projects_url, alert: 'Project not found'
  end

  def set_times
    return unless @project.project_updates.any?

    @days_since_start = @project.project_updates.map(&:manually_edited_datetime).map(&:to_date).uniq

    time_intervals = []

    @project.project_updates.order(manually_edited_datetime: :asc).each_slice(2) do |start, stop|
      time_intervals << if stop.nil?
                          (Time.current.in_time_zone("America/New_York") - start.manually_edited_datetime)
                        else
                          (stop.manually_edited_datetime - start.manually_edited_datetime)
                        end
    end

    @hours_worked = time_intervals.reduce(0) do |total_time, time_interval|
      total_time + time_interval
    end / 3600
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

# Helper for Project views
module ProjectsHelper
  def current_status_in_words(project_update:)
    get_status(update: project_update)
  end

  def current_status_in_past(project:)
    last_update = last_update(project:)
    return 'Not Started' if last_update.nil?

    get_status(update: last_update)
  end

  def get_status(update:)
    update.status.humanize
  end

  def last_update(project:)
    project.project_updates.order(manually_edited_datetime: :desc).first
  end

  def last_update_current_status(project:)
    last_update(project:)&.status
  end

  def last_update_is_started?(project:)
    last_update(project:)&.started? || false
  end
end

app/views/projects/_form.html.erb
<%= form_with model: project do |form| %>
  <div class="PROJECT-NAME-INPUT">
    <%= form.label :name, class: "block mt-2 text-sm font-medium text-gray-900" %>
    <%= form.text_field :name, placeholder: "Add a new project...", class: "input bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
  </div>
  <% if project_update %>
    <%= render "project_updates/form", project: project, project_update: project_update, form: form %>
  <% end %>
  <div class="flex justify-center sm:justify-end PROJECT-FORM-BUTTONS">
    <%= link_to "Cancel", :back, class: "btn py-2 bg-gray-100" %>
    <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<% next_update_is_start = !last_update_is_started?(project: project) %>
<% status = last_update_current_status(project: project) %>
<div class="col-span-2 border-b-2">
  <%= link_to(project_path(project), {class: "flex"}) do %>
    <div class="flex flex-col">
      <div class="font-semibold text-sky-900">
        <%= project.name %>
      </div>
      <div class="flex items-center text-xs">
        Current Status: 
        <strong>&nbsp<%= current_status_in_past(project: project) %></strong>
      </div>
    </div>
    <% if project.project_updates.last&.note.present? %>
      <div class="pl-4 sm:flex hidden items-center text-sm truncate max-w-[265px]">
        Last note: 
        <p class="truncate">&nbsp<%= project.project_updates.last&.note %></p>
      </div>
    <% end %>
  <% end %>
</div>
<% if project.project_access_controls.select(:level).map(&:level).include?("owner") %>
  <div class="col-span-1 flex justify-end border-b-2 BUTTONS-CONTAINER">
    <div class="START-STOP-BUTTON">
      <% if next_update_is_start %>
        <%= link_to "Start", edit_project_path(project), class: "btn bg-green-100", data: { turbo_frame: "modal" } %>
      <% else %>
        <%= link_to "Stop", edit_project_path(project), class: "btn bg-red-100", data: { turbo_frame: "modal" } %>
      <% end %>
    </div>
    <div class="DELETE-BUTTON">
      <%= link_to "🗑", project_path(project),
                    data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this project ?' },
                    class: "btn px-1 text-white ml-2" %>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% next_update_is_start = !last_update_is_started?(project: @project) %>
<% project_heading = next_update_is_start ? "Start" : "Stop" %>
<%= turbo_frame_tag "modal" do %>
  <!-- This example requires Tailwind CSS v2.0+ -->
  <!-- TODO: THIS IS MODAL BOILER PLATE. REFACTOR THIS OUT SO THAT YOU ONLY NEED TO RENDER THE FORM BELOW -->
  <div class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <div class="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
      <!--
      Background overlay, show/hide based on modal state.
      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
      <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>
      <!-- This element is to trick the browser into centering the modal contents. -->
      <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
      <!--
      Modal panel, show/hide based on modal state.
      Entering: "ease-out duration-300"
        From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        To: "opacity-100 translate-y-0 sm:scale-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100 translate-y-0 sm:scale-100"
        To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
    -->
      <div class="inline-block align-middle bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:max-w-lg sm:w-full sm:p-6">
        <h1 class="font-bold text-2xl mb-3"><%= project_heading %> Project</h1>
        <div id="<%= dom_id @project %>">
          <%= render "form", project: @project, project_update: @project_update %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/index.html.erb
<% if current_user %>
  <div id="new-project" class="flex flex-col items-center NEW-PROJECT-CONTAINER">
    <h1 class="font-bold text-2xl">New Project</h1>
    <div class="mb-4">
      <%= form_with model: @new_project do |form| %>
        <div class="flex items-baseline">
          <%= form.text_field :name, placeholder: "Add a new project...", class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
          <%= form.button "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div id="new-project" class="flex flex-col items-center NEW-PROJECT-CONTAINER">
    <h1 class="font-bold text-2xl">Sign in to start !</h1>
  </div>
<% end %>
<div id="projects" class="flex flex-col min-w-[325px] max-w-[768px] my-0 mx-auto PROJECTS-CONTAINER">
  <% if @projects.empty? %>
    <p class="font-bold text-l mb-2 text-center">Save your first project above to get started !</p>
  <% else %>
    <h1 class="font-bold text-xl mb-2">Projects</h1>
    <div class="grid grid-cols-3 gap-y-4" data-controller="projects">
      <%= render @projects %>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<%= link_to "⬅️ back", projects_path, class: "btn py-2 bg-gray-200 text-black" %>
<% nav_list = [] %>
<div class="flex items-baseline justify-between pt-4">
  <h1 class="font-bold text-2xl"><%= @project.name %></h1>
  <%= link_to "New Update", edit_project_path(@project), class: "btn ml-2 px-2 bg-black text-white", data: { turbo_frame: "modal" } %>
</div>
<% if @project.project_updates.any? %>
  <ul class="flex items-center overflow-x-auto gap-6 snap-mandatory snap-x py-6 before:shrink-0 before:w-[30vw] after:shrink-0 after:w-[30vw] ROJECT-UPDATE-CARDS">
    <% last_update = nil %>
    <% @project.project_updates.order(manually_edited_datetime: :desc).each do |project_update| %>
      <% card_title = project_update.status&.humanize %>
      <% text_color =  %>
      <div class="flex items-center first-of-type:hidden ELLIPSIS">
        <div class="flex text-slate-800 rounded-sm">
          <% if last_update.present? %>
            <% text_color = "text-green-500" if last_update.started? %>
            <div class="px-2">
              <% if last_update.stopped? %>
                <strong class="text-green-500">
                <% else %>
                  <strong class="text-red-500">
                  <% end %>
                  <%= TimeDifference.between(
              project_update.manually_edited_datetime, last_update.manually_edited_datetime
    ).in_hours.round(0) %>
                </strong>
              </div>
            <% end %>
          </div>
        </div>
        <% last_update = project_update %>
        <% if card_title != "Started" %>
          <% if card_title == "Finished" %>
            <li id=<%= project_update.id %> class="bg-blue-500 shrink-0 snap-center flex justify-between max-w-sm rounded-lg overflow-hidden shadow-lg p-4 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300 PROJECT-UPDATE-CARD">
            <% else %>
              <li id=<%= project_update.id %> class="bg-red-500 shrink-0 snap-center flex justify-between max-w-sm rounded-lg overflow-hidden shadow-lg p-4 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300 PROJECT-UPDATE-CARD">
              <% end %>
            <% else %>
              <li id=<%= project_update.id %> class="bg-green-500 shrink-0 snap-center flex justify-between max-w-sm rounded-lg overflow-hidden shadow-lg p-4 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300 PROJECT-UPDATE-CARD">
              <% end %>
              <%= link_to(edit_project_update_path(project_update), {class: "text-white", data: { turbo_frame: "modal" }}) do %>
                <div class="text-lg font-semibold">
                  <%= card_title %>
                </div>
                <div>
                  <div>
                    Time: <%= project_update.manually_edited_datetime.strftime("%_m/%-d %l:%M%P") %>
                  </div>
                  <% if project_update.reason.present? %>
                    <div>
                      Reason: <%= project_update.reason&.humanize %>
                    </div>
                  <% end %>
                  <% if project_update.note.present? %>
                    <div>
                      Note: <%= project_update.note %>
                    </div>
                  <% end %>
                </div>
              <% end %>
              <div class="flex flex-col justify-center items-center">
                <%# NOTE ! DELETE BUTTON FOR PROJECT UPDATES HERE. MUST DECIDE IF WE WANT THIS FUNCTIONALITY %>
                <%= link_to "🚮", project_update_path(project_update), class: "btn px-1 text-xl ml-4", data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this update ?' } %>
              </div>
            </li>
            <% nav_list.push({id: project_update.id, title: card_title, date: project_update.manually_edited_datetime.strftime("%_m/%-d at %l:%M%P")}) %>
          <% end %>
        </ul>
        <% if @hours_worked %>
          <div class="text-base sm:text-lg text-center py-2 TIME-CONTAINER">
            <div class="TOTAL-TIME-WORKED">
              <strong><%= @hours_worked.round(0) %></strong> total hours worked
              <% if last_update_is_started?(project: @project) %>
                and counting ⏱
              <% end %>
            </div>
            <% if @days_since_start %>
              <div class="TOTAL-TIME-SINCE-PROJECT-BEGAN">
                <strong><%= @days_since_start.count %></strong> day<%= "s" if @days_since_start.count > 1 %> total worked on project
              </div>
            <% end %>
          </div>
        <% end %>
        <nav class="flex flex-col items-center">
          <% nav_list.each do |nav_list_item| %>
            <li class="py-2 list-none">
              <%= link_to "#{nav_list_item.fetch(:title)} on #{nav_list_item.fetch(:date)}", "##{nav_list_item.fetch(:id)}", class: "btn bg-gray-500 text-white" %>
            </li>
          <% end %>
        </nav>
      <% else %>
        No updates
      <% end %>